---
version: '3.5'

services:
  photoprism:
    # Use photoprism/photoprism:preview instead for testing preview builds:
    image: photoprism/photoprism:latest
    restart: on-failure:10
    container_name: photoprism 
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: admin
      PHOTOPRISM_HTTP_PORT: 2342                      # Built-in Web server port
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"             # Improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DEBUG: "false"                       # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                      # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                    # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "true"                 # Enable experimental features
      PHOTOPRISM_DISABLE_WEBDAV: "false"              # Disable built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"            # Users can not view or change settings
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"          # Don't use TensorFlow for image classification
      PHOTOPRISM_DETECT_NSFW: "false"                 # Flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                  # Allow uploads that MAY be offensive
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"          # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: "mysql"             # Use MariaDB (or MySQL) instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "${DATABASE_SERVER}" # MariaDB database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"          # MariaDB database schema name
      PHOTOPRISM_DATABASE_USER: "${DATABASE_USER}"    # MariaDB database user name
      PHOTOPRISM_DATABASE_PASSWORD: "${DATABASE_PASS}" # MariaDB database user password
      PHOTOPRISM_SITE_URL: "https://${DOMAIN}/"         # Public PhotoPrism URL
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: "${SITE_AUTHOR}"
      PHOTOPRISM_SPONSOR: "true"
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    user: "${UID}:${GID}"
    labels:
      - traefik.http.routers.photoprism-http.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.photoprism-http.entrypoints=http
      - traefik.http.routers.photoprism-http.middlewares=redirect
      - traefik.http.routers.photoprism-https.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.photoprism-https.entrypoints=https
      - traefik.http.routers.photoprism-https.tls=true
      - traefik.http.routers.photoprism-https.tls.certresolver=letsencrypt
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https
      - com.ouroboros.enable=true
    volumes:
      # Your photo and video files ([local path]:[container path]):
      - "${PHOTOPRISM_ORIGINALS}:/photoprism/originals"
      # Permanent storage for settings, index & sidecar files (DON'T REMOVE):
      - "${PHOTOPRISM_STORAGE}:/photoprism/storage"
    networks:
      - web_services

networks:
  web_services:
    external: true

